### ISSUE TITLE
Pre-trained NeRF model

### ISSUE THREAD

**Issue by starcxl** [ayaanzhaque/instruct-nerf2nerf#21]
Many thanks for your awesome job!

May I ask that could you please provide your pre-trained NeRF model parameters on the datasets used in this paper? Just avoid more users training it again to waste computing sources. Pretty thanks!

**Comment by ayaanzhaque** [comment]
Sure, I can release them soon. Training a nerfacto model is quite quick though!

**Comment by ayaanzhaque** [comment]
I've decided not to provide pre-trained models primarily because as the main nerfstudio repository is updated, the Nerfacto configuration may change, meaning the pre-trained models that I provide will no longer be able to be loaded. Training a nerfacto model shouldn't take more than 3g of memory and an hour of training time!
