### ISSUE TITLE
a small question about the CLIP Direction Consistency Loss

### ISSUE THREAD

**Issue by Jonlysun** [ayaanzhaque/instruct-nerf2nerf#28]
Hi, thanks for your excellent work. I have a small question about the CLIP directional consistency loss described in Appendix C, which is calculated as _(C(ei) - C(oi)) * (C(ei+1) - C(ei))_. I don't know if this is a writing error and what you really mean is _(C(oi+1) - C(oi)) * (C(ei+1) - C(ei))_

**Comment by Jonlysun** [comment]
Thanks for your reply. I calculate this loss with:   F.cosine_similarity(C(oi+1) - C(oi), C(ei+1) - C(ei)) now. I wonder if this is true to use cosine_similarity？

**Comment by ayaanzhaque** [comment]
I will provide the script to perform the calculation soon!

**Comment by ayaanzhaque** [comment]
Hi, here are the metrics for clip, sorry for the wait!

https://github.com/ayaanzhaque/instruct-nerf2nerf/tree/main/metrics

**Comment by viridityzhu** [comment]
Hi, thanks a lot for clarifying the writing error in the appendix! It was very helpful because it trapped me for a long while...

But I still have some doubts about the shared `metrics.py`, where the function returns:
```python
return sim_0, sim_1, sim_direction, sim_image
```
Based on my understanding, these correspond to:
1. similarity between image0 and text0
2. similarity between image1 and text1
3. similarity between the image direction and the text direction
4. similarity between image0 and image1

However, I couldn't find the implementation for the directional consistency loss, which I believe should measure the similarity between two types of image directions.

Could you please provide further insights or corrections to my understanding? Thanks again!
