### ISSUE TITLE
Phase one uses instant-ngp to pretrain NeRF

### ISSUE THREAD

**Issue by lxmcwt** [ayaanzhaque/instruct-nerf2nerf#36]
The in2n algorithm divides the training process into two phases. The first phase pretrains a NeRF model using the nerfacto algorithm, but I would like to try other algorithms such as instant-ngp. However, I have encountered errors when attempting to use instant-ngp. Do you have any suggestions for how to resolve this issue?
![1](https://github.com/ayaanzhaque/instruct-nerf2nerf/assets/49682197/10e2e88a-f943-486f-b582-8fad362f3fa9)

**Comment by ayaanzhaque** [comment]
Currently the model that IN2N uses is the nerfacto model, which is why you have all these state_dict errors. 

https://github.com/ayaanzhaque/instruct-nerf2nerf/blob/main/in2n/in2n.py#L34

If you go here, you can adjust the code to basically have IN2N inherit the Instant-NGP model. You may have to adjust some code here as well as in the pipeline to match instant-ngp. However, I do see that Instant-NGP in nerfstudio uses a different pipeline model, which may make it challenging to make the swap.
