### ISSUE TITLE
Training duration question

### ISSUE THREAD

**Issue by Iliceth** [ayaanzhaque/instruct-nerf2nerf#75]
Not realy an issue, just hoping to learn about the normal behaviour of the software. I hope you don't mind I post this here. If there are other places I should go for that, feel free to let me know.

I have a RTX 3060 12GB and training the bear example to 30000 takes about 25 minutes on my computer. If I then start in2n-small or in2n-tiny to use the prompt "make it a grizzly", it then estimates and actually takes about 24 hours to do another 30000.

Is this a normal duration? I know I didn't use any downsampling of the images at all, but the difference between initial training and the instructed version is quite steep, therefor the question.

I read and so am aware 30000 extra steps is not necessary and that is also my experience, but please let me know about the duration estimation. Thanks!

**Comment by ayaanzhaque** [comment]
This should check out I think. I think in practice, you only have to train in2n for 10k iters, so that usually will take an hour.

**Comment by bjkim95** [comment]
For running  `ns-train in2n` , set `--max-num-iterations` as **30000 + <desired iterations>**.
Here, 30000 is the default training iteration of **nerfacto**.
And, since in2n starts from nerfacto checkpoints, it counts the number of iterations from 30000.

So, if you set --max-num-iterations as 60000 (the actual iterations for in2n is 30000), you may see the correct ETA.

I think the reason for the wrong ETA is that the default value of --max-num-iterations is 15,000, which is set smaller than the default iterations of nerfacto.
