### ISSUE TITLE
Question about ablation in the paper: "Ours + StableDiffusion"

### ISSUE THREAD

**Issue by lukasHoel** [ayaanzhaque/instruct-nerf2nerf#9]
Hi,

thanks for releasing the code/paper, I really enjoyed reading it!
While looking at the ablations, I was wondering how exactly you implemented "Ours + StableDiffusion":

- Did you apply the img2img task with StableDiffusion (e.g. as in SDEdit)? 

- Did you estimate monocular depth and apply the depth2img task with a finetuned StableDiffusion model + start from noised input image as in SDEdit?

These two would provide some form of image conditioning, but only using the current rendered image as input (without the original image as additional conditioning).
So is my understanding correct that the edits with these approaches are too low-quality / inconsistent and that the InstructPix2Pix performs better at this task, which is why you get so much better results in the end?

Thank you so much in advance!
Lukas

**Comment by ayaanzhaque** [comment]
Hi!

So our implementation of "Ours + StableDiffusion" is simply using our Iterative Dataset Update method but instead of editing the images with InstructPix2Pix, we edit the image using Stable Diffusion. Therefore, there is no image conditioning. We did not apply the img2img task nor estimate monocular depth. I agree that the two ideas you listed would provide Stable Diffusion with some form of image conditioning. 

The reason the "Ours + StableDiffusion" result looks poor is that when you input the current render and try to edit it, 1) the text prompt is hard to formulate as we cannot use a simple text instruction, but rather we have to come up with an elaborate prompt to describe a real-world image, and 2) there is no grounding in the original image to enforce consistency. This is why the results look unreasonable. Let me know if you have any other questions!

**Comment by lukasHoel** [comment]
Thank you very much for the response, that makes sense clears up the implementation for me :)
